//! Compatibility route manifest for the migrated Go HTTP surface.
//!
//! This module keeps the Rust router honest during the migration: every known
//! Go HTTP route is represented in [`COMPATIBILITY_ROUTE_MANIFEST`]. The runtime
//! stub router has been removed now that all manifest entries are implemented.

/// Migration status for a route from the Go compatibility manifest.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompatibilityRouteStatus {
    /// The route dispatches to a Rust handler with migrated behavior.
    Implemented,
    /// The route is listed in the manifest but has no migrated Rust handler yet.
    Stub,
}

/// One method/path entry from the Go route manifest.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CompatibilityRoute {
    /// HTTP method from the Go route declaration, with Gin `ANY` expanded.
    pub method: &'static str,
    /// Axum route pattern for the Go path, including converted params.
    pub path: &'static str,
    /// Whether this route is implemented or still a compatibility stub.
    pub status: CompatibilityRouteStatus,
}

macro_rules! route {
    ($method:literal, $path:literal, $status:ident) => {
        CompatibilityRoute {
            method: $method,
            path: $path,
            status: CompatibilityRouteStatus::$status,
        }
    };
}

/// Explicit manifest for the Go routes known to the Rust migration.
pub const COMPATIBILITY_ROUTE_MANIFEST: &[CompatibilityRoute] = &[
    route!("GET", "/hello", Implemented),
    route!("GET", "/", Implemented),
    route!("HEAD", "/", Implemented),
    route!("POST", "/api/login", Implemented),
    route!("GET", "/api/logout", Implemented),
    route!("POST", "/api/logout", Implemented),
    route!("POST", "/api/change/password", Implemented),
    route!("GET", "/api/user", Implemented),
    route!("POST", "/api/user", Implemented),
    route!("GET", "/api/init", Implemented),
    route!("POST", "/api/init", Implemented),
    route!("GET", "/api/install/steamcmd", Implemented),
    route!("GET", "/api/statistics/active/user", Implemented),
    route!("GET", "/api/statistics/top/death", Implemented),
    route!("GET", "/api/statistics/top/login", Implemented),
    route!("GET", "/api/statistics/top/active", Implemented),
    route!("GET", "/api/statistics/rate/role", Implemented),
    route!("GET", "/api/statistics/regenerate", Implemented),
    route!("GET", "/api/dst/version", Implemented),
    route!("POST", "/api/dst/home/server", Implemented),
    route!("POST", "/api/dst/home/server/detail", Implemented),
    route!("GET", "/api/dst/lobby/server/detail", Implemented),
    route!("GET", "/api/dst/home/server2", Implemented),
    route!("GET", "/api/dst/home/server/detail2", Implemented),
    route!("GET", "/api/dst-static/{*filepath}", Implemented),
    route!("POST", "/api/dst-static/{*filepath}", Implemented),
    route!("PUT", "/api/dst-static/{*filepath}", Implemented),
    route!("DELETE", "/api/dst-static/{*filepath}", Implemented),
    route!("PATCH", "/api/dst-static/{*filepath}", Implemented),
    route!("HEAD", "/api/dst-static/{*filepath}", Implemented),
    route!("OPTIONS", "/api/dst-static/{*filepath}", Implemented),
    route!("CONNECT", "/api/dst-static/{*filepath}", Implemented),
    route!("TRACE", "/api/dst-static/{*filepath}", Implemented),
    route!("GET", "/assets/{*filepath}", Implemented),
    route!("HEAD", "/assets/{*filepath}", Implemented),
    route!("GET", "/misc/{*filepath}", Implemented),
    route!("HEAD", "/misc/{*filepath}", Implemented),
    route!("GET", "/static/js/{*filepath}", Implemented),
    route!("HEAD", "/static/js/{*filepath}", Implemented),
    route!("GET", "/static/css/{*filepath}", Implemented),
    route!("HEAD", "/static/css/{*filepath}", Implemented),
    route!("GET", "/static/img/{*filepath}", Implemented),
    route!("HEAD", "/static/img/{*filepath}", Implemented),
    route!("GET", "/static/fonts/{*filepath}", Implemented),
    route!("HEAD", "/static/fonts/{*filepath}", Implemented),
    route!("GET", "/static/media/{*filepath}", Implemented),
    route!("HEAD", "/static/media/{*filepath}", Implemented),
    route!("GET", "/favicon.ico", Implemented),
    route!("HEAD", "/favicon.ico", Implemented),
    route!("GET", "/asset-manifest.json", Implemented),
    route!("HEAD", "/asset-manifest.json", Implemented),
    route!("GET", "/steam/dst/news", Implemented),
    route!("GET", "/api/mod/search", Implemented),
    route!("GET", "/api/mod/{modId}", Implemented),
    route!("PUT", "/api/mod/{modId}", Implemented),
    route!("GET", "/api/mod", Implemented),
    route!("DELETE", "/api/mod/{modId}", Implemented),
    route!("DELETE", "/api/mod/setup/workshop", Implemented),
    route!("GET", "/api/mod/modinfo/{modId}", Implemented),
    route!("POST", "/api/mod/modinfo", Implemented),
    route!("POST", "/api/mod/modinfo/file", Implemented),
    route!("PUT", "/api/mod/modinfo", Implemented),
    route!("GET", "/api/mod/ugc/acf", Implemented),
    route!("DELETE", "/api/mod/ugc", Implemented),
    route!("GET", "/ws", Implemented),
    route!("POST", "/api/file/ugc/upload", Implemented),
    route!("POST", "/api/file/background", Implemented),
    route!("GET", "/api/file/background", Implemented),
    route!("GET", "/api/cluster", Implemented),
    route!("POST", "/api/cluster", Implemented),
    route!("PUT", "/api/cluster", Implemented),
    route!("DELETE", "/api/cluster", Implemented),
    route!("GET", "/api/cluster/level", Implemented),
    route!("PUT", "/api/cluster/level", Implemented),
    route!("POST", "/api/cluster/level", Implemented),
    route!("DELETE", "/api/cluster/level", Implemented),
    route!("GET", "/api/game/8level/status", Implemented),
    route!("GET", "/api/game/8level/status/stream", Implemented),
    route!("GET", "/api/game/8level/start", Implemented),
    route!("GET", "/api/game/8level/stop", Implemented),
    route!("GET", "/api/game/8level/start/all", Implemented),
    route!("GET", "/api/game/8level/stop/all", Implemented),
    route!("GET", "/api/game/8level/clusterIni", Implemented),
    route!("POST", "/api/game/8level/clusterIni", Implemented),
    route!("GET", "/api/game/8level/players", Implemented),
    route!("GET", "/api/game/8level/players/all", Implemented),
    route!("GET", "/api/game/8level/adminilist", Implemented),
    route!("GET", "/api/game/8level/whitelist", Implemented),
    route!("GET", "/api/game/8level/blacklist", Implemented),
    route!("POST", "/api/game/8level/adminilist", Implemented),
    route!("POST", "/api/game/8level/whitelist", Implemented),
    route!("POST", "/api/game/8level/blacklist", Implemented),
    route!("POST", "/api/game/8level/command", Implemented),
    route!("GET", "/api/game/8level/udp/port", Implemented),
    route!("GET", "/api/game/preinstall", Implemented),
    route!("GET", "/api/share/keyCer", Implemented),
    route!("GET", "/api/share/keyCer/reflush", Implemented),
    route!("GET", "/api/share/keyCer/enable", Implemented),
    route!("POST", "/api/share/cluster/import", Implemented),
    route!("GET", "/share/cluster", Implemented),
    route!("GET", "/api/game/player", Implemented),
    route!("GET", "/api/game/player/adminlist", Implemented),
    route!("POST", "/api/game/player/adminlist", Implemented),
    route!("GET", "/api/game/player/blacklist", Implemented),
    route!("POST", "/api/game/player/blacklist", Implemented),
    route!("DELETE", "/api/game/player/blacklist", Implemented),
    route!("DELETE", "/api/game/player/adminlist", Implemented),
    route!("GET", "/api/player/log", Implemented),
    route!("POST", "/api/player/log/delete", Implemented),
    route!("GET", "/api/game/sent/broadcast", Implemented),
    route!("GET", "/api/game/kick/player", Implemented),
    route!("GET", "/api/game/kill/player", Implemented),
    route!("GET", "/api/game/respawn/player", Implemented),
    route!("GET", "/api/game/rollback", Implemented),
    route!("GET", "/api/game/regenerateworld", Implemented),
    route!("POST", "/api/game/master/console", Implemented),
    route!("POST", "/api/game/caves/console", Implemented),
    route!("GET", "/api/game/operate/player", Implemented),
    route!("GET", "/api/game/backup/restore", Implemented),
    route!("GET", "/api/game/archive", Implemented),
    route!("GET", "/api/game/clean", Implemented),
    route!("GET", "/api/game/clean/level", Implemented),
    route!("GET", "/api/game/clean/level/all", Implemented),
    route!("GET", "/api/game/announce/setting", Implemented),
    route!("POST", "/api/game/announce/setting", Implemented),
    route!("GET", "/api/game/level/server/log", Implemented),
    route!("GET", "/api/game/level/server/chat/log", Implemented),
    route!("GET", "/api/game/level/server/download", Implemented),
    route!("GET", "/api/game/dst-admin-go/log", Implemented),
    route!("GET", "/api/game/dst-admin-go/log/download", Implemented),
    route!("GET", "/api/game/config", Implemented),
    route!("POST", "/api/game/config", Implemented),
    route!("GET", "/api/game/update", Implemented),
    route!("GET", "/api/game/system/info", Implemented),
    route!("GET", "/api/game/system/info/stream", Implemented),
    route!("GET", "/api/dst/config", Implemented),
    route!("POST", "/api/dst/config", Implemented),
    route!("GET", "/api/kv", Implemented),
    route!("POST", "/api/kv", Implemented),
    route!("GET", "/api/game/backup", Implemented),
    route!("POST", "/api/game/backup", Implemented),
    route!("DELETE", "/api/game/backup", Implemented),
    route!("PUT", "/api/game/backup", Implemented),
    route!("GET", "/api/game/backup/download", Implemented),
    route!("POST", "/api/game/backup/upload", Implemented),
    route!("POST", "/api/game/backup/snapshot/setting", Implemented),
    route!("GET", "/api/game/backup/snapshot/setting", Implemented),
    route!("GET", "/api/game/backup/snapshot/list", Implemented),
    route!("GET", "/api/task", Implemented),
    route!("POST", "/api/task", Implemented),
    route!("DELETE", "/api/task", Implemented),
    route!("GET", "/api/task/instruct", Implemented),
    route!("GET", "/api/game/log/stream", Implemented),
    route!("GET", "/api/web/link", Implemented),
    route!("POST", "/api/web/link", Implemented),
    route!("DELETE", "/api/web/link", Implemented),
    route!("POST", "/webhook", Implemented),
    route!("GET", "/api/dst/map/gen", Implemented),
    route!("GET", "/api/dst/map/image", Implemented),
    route!("GET", "/api/dst/map/has/walrusHut/plains", Implemented),
    route!("GET", "/api/dst/map/session/file", Implemented),
    route!("GET", "/api/dst/map/player/session/file", Implemented),
    route!("GET", "/api/auto/check2", Implemented),
    route!("POST", "/api/auto/check2", Implemented),
];
