export const routes = {
  login: '/login',
  init: '/init',
  dashboard: '/dashboard',
  panel: '/panel',
  clusterIni: '/home/clusterIni',
  adminlist: '/home/adminlist',
  whitelist: '/home/whitelist',
  blacklist: '/home/blacklist',
  levels: '/levels/levels',
  selectorMod: '/levels/selectorMod',
  preinstall: '/levels/preinstall',
  genMap: '/levels/genMap',
  mod: '/mod',
  backup: '/backup',
  playerLog: '/playerLog',
  setting: '/setting',
  lobby: '/lobby',
  help: '/help',
  userProfile: '/userProfile',
} as const
